quizapp/urls.py
from django.contrib import admin
from django.urls import path
from qbank import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',views.home,name='home'),
    path('all_questions/',views.all_questions,name='all_questions'),
    path('single_question/<int:pk>/',views.single_question,name='single_question'),
    path('delete_question/<int:id>/',views.delete_question,name='delete_question'),
    path('questions/',views.questions,name='questions'),
    path('createQuestion/',views.createQuestion,name='createQuestion'),
    path('createAnswer/',views.createAnswer,name='createAnswer'),

]

qbank/models.py
from django.db import models


class student(models.Model):
	name=models.CharField(max_length=10)

#Create your models here.
class Category(models.Model):
	name=models.CharField(max_length=250, unique=True)
	description=models.TextField(max_length=250)
	is_active= models.BooleanField(default='False')
	#sequence=
	def __str__(self):
		return self.name


class Question(models.Model):
	question_text=models.CharField(max_length=50, unique=True)
	score= models.IntegerField(default=0)
	#negative_score=
	#data_type=
	is_active= models.BooleanField(default='False')
	category= models.ForeignKey(Category, on_delete=models.CASCADE)
	#sequence=
	def __str__(self):
		return self.question_text

class Answer(models.Model):
	question_text= models.ForeignKey(Question, on_delete=models.CASCADE)
	choice1 = models.CharField(max_length=50, unique=True)
	choice2 = models.CharField(max_length=50, unique=True)
	choice3 = models.CharField(max_length=50, unique=True)
	choice4 = models.CharField(max_length=50, unique=True)
	answer_key=models.IntegerField()
	answer_value=models.CharField(max_length=50, unique=True)#correct_answer 
	is_active=models.BooleanField(default='False')
	score=models.IntegerField(default=0)
	negative_score=models.IntegerField(default=0)
	sequence=models.IntegerField(default=0)
	is_correct_answer=models.BooleanField(default='False')
	def __str__(self):
		return self.question_text


qbank/forms.py
from django import forms 
from .models import Answer,Question

class CreateQuestionForm(forms.ModelForm):
	print("working")
	class Meta:
		model=Question
		fields='__all__'

class CreateAnswerForm(forms.ModelForm):
	print("working")
	class Meta:
		model=Answer
		fields='__all__'

qbank/views.py
from django.shortcuts import render,redirect
from .models import Question,Category
from .forms import CreateQuestionForm,CreateAnswerForm
from django.contrib import messages

# Create your views here.
def home(request):
	cat=Category.objects.all()
	que=Question.objects.all()

	print(cat)
	return render(request,'qbank/home.html',context={'objects':que,'cat':cat,})

def all_questions(request):
	que=Question.objects.all()
	return render(request,'qbank/all_questions.html',context={'objects':que,})

def single_question(request,pk=id):	
	que=Question.objects.get(pk=pk)
	return render(request,'qbank/single_question.html',context={'object':que,})

def questions(request):
	ans=""
	if request.method == "POST":
		ans=request.POST.get('choice')
		que=Question.objects.all()

	else:
		que=Question.objects.all()
	context={'objects':que,'ans':ans}
	# # print(context)
	return render(request,'qbank/question_ans.html',context)

def createQuestion(request):

	if request.method == "POST":
		form=CreateQuestionForm(request.POST)
		# que=form.cleaned_data.get('question_text')
		# print(que)
		if form.is_valid():
			form.save()
			messages.success(request, ('Your Question was successfully added!'))
		else:
			messages.error(request, 'Error saving form')
		
	form=CreateQuestionForm()
	context={'form':form,
	}
	
	return render(request,'qbank/create_question.html',context)

def createAnswer(request):
	print("1")
	if request.method == "POST":
		form=CreateAnswerForm(request.POST)
		
		if form.is_valid():
			print("im in form")

			form.save()
			messages.success(request, ('Your Question was successfully added!'))
		else:
			messages.error(request, 'Error saving form')
		
	form=CreateAnswerForm()
	context={'form':form,
	}
	
	return render(request,'qbank/create_ans.html',context)

def delete_question(request,id):
	que=Question.objects.get(id=id)
	que.delete()
	return redirect('all_questions')



qbank/templates/qbank/all_questions.html

<html>
<head>
	<title></title>
</head>
<body>
	
<form action="#" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>Questions</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for que in objects %}
    <h3>{{forloop.counter}}.<a href="{% url 'single_question' que.id %}" style="text-decoration: none;">{{que.question_text}}<a></h3>
    {% endfor %}
    
    </fieldset>

</form>
</body>
</html>

qbank/templates/qbank/create_ans.html
<html>
<head>
	<title></title>
</head>
<body>
{% if messages %}
	<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
	</ul>
{% endif %}

<form action="{% url 'createAnswer' %}" method="POST">
{% csrf_token %}
{{form.as_p}}
<input type="submit"></input>
</form>

</body>
</html>

qbank/templates/qbank/create_question.html
<html>
<head>
	<title></title>
</head>
<body>
<form action="{% url 'createQuestion' %}" method="POST">
{% csrf_token %}


{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
{{form.as_p}}
<input type="submit"></input>
</form>
</body>
</html>

qbank/templates/qbank/crete_question.html
<html>
<head>
	<title></title>
</head>
<body>
<form action="{% url 'createQuestion' %}" method="POST">
{% csrf_token %}


{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
{{form.as_p}}
<input type="submit"></input>
</form>
</body>
</html>

qbank/templates/qbank/home.html

<html>
<head>
	<title></title>
</head>
<body>
<h1 style="font-size:30px;">Online Quiz</h1>
<h3>select language:<br>
	
{% for category in cat %}
	<a href="">{{category}}</a><br>
{% endfor %}</h3>
<!-- <h4><a href="">Read Question/take test</a></h4> -->
<h4><a href="{% url 'createQuestion' %}">Create New Question</a></h4>
<h4><a href="">Update Question</a></h4>
<h4><a href="">Delete Question</a></h4>

</body>
</html>


<!-- <form action="#" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
</fieldset>
<input type="submit" value="Vote">
</form> -->

qbank/templates/qbank/question.html
<html>
<head>
	<title></title>
</head>
<body>
	<form action="{% url 'questions' %}" method='POST'>
		{% csrf_token %}
	question display:
	{% for que in objects %}
	<h2>{{que.question_text}}</h2>
	{% for i in que.answer_set.all %}

	<input type="radio" name="choice" id="1" value="{{i.choice1}}">
    <label for="1">{{i.choice1}}</label><br>
    <input type="radio" name="choice" id="2" value="{{i.choice2}}">
    <label for="2">{{i.choice2}}</label><br>
    <input type="radio" name="choice" id="3" value="{{i.choice3}}">
    <label for="3">{{i.choice3}}</label><br>
    <input type="radio" name="choice" id="4" value="{{i.choice4}}">
    <label for="4">{{i.choice4}}</label><br>
    {% if ans %}
    <h4>Ans:{{ans}}</h4>
    {% else %}
    <h4>Ans:</h4>
    {% endif %}
	{% endfor %}
	<input type="submit"></input>
	{% endfor %}

	
</form>



</body>
</html>

qbank/templates/qbank/question_ans.html
<html>
<head>
	<title></title>
</head>
<body>
	<form action="{% url 'questions' %}" method='POST'>
		{% csrf_token %}
	question display:
	{% for que in objects %}
	<h2>{{que.question_text}}</h2>
	{% for i in que.answer_set.all %}

	<input type="radio" name="choice" id="1" value="{{i.choice1}}">
    <label for="1">{{i.choice1}}</label><br>
    <input type="radio" name="choice" id="2" value="{{i.choice2}}">
    <label for="2">{{i.choice2}}</label><br>
    <input type="radio" name="choice" id="3" value="{{i.choice3}}">
    <label for="3">{{i.choice3}}</label><br>
    <input type="radio" name="choice" id="4" value="{{i.choice4}}">
    <label for="4">{{i.choice4}}</label><br>
    {% if ans %}
    <h4>Ans:{{ans}}</h4>
    {% else %}
    <h4>Ans:</h4>
    {% endif %}
	{% endfor %}
	<input type="submit"></input>
	{% endfor %}

	
</form>



</body>
</html>

qbank/templates/qbank/single_question.html
<html>
<head>
	<title></title>
</head>
<body>
	<form action="{% url 'questions' %}" method='POST' style="font-size:20px;">
		{% csrf_token %}
	question display:
	<h4>{{object.question_text}}<button><a href="{% url 'delete_question' object.id %}" class="btn btn-danger" >Delete</a></button></h4><br>
	{% for i in object.answer_set.all %}
	<input type="radio" name="choice" id="1" value="{{i.chice1}}">
    <label for="1">{{i.choice1}}</label><br>
    <input type="radio" name="choice" id="2" value="{{i.choice2}}">
    <label for="2">{{i.choice2}}</label><br>
    <input type="radio" name="choice" id="3" value="{{i.choice3}}">
    <label for="3">{{i.choice3}}</label><br>
    <input type="radio" name="choice" id="4" value="{{i.choice4}}">
    <label for="4">{{i.choice4}}</label><br>
    {% endfor %}
    <br>
	<button class="btn btn-deault"><a href="{% url 'all_questions' %}" class="btn btn-primary">Back</a></button>
	

	
</form>



</body>
</html>